### ISSUE TITLE
data requirement

### ISSUE THREAD

**Issue by clotilda-0** [XiaoleiQinn/SITSMamba#1]
from utils.dataset import ijgiDataset as Dataset
ModuleNotFoundError: No module named 'utils'

Fix please @XiaoleiQinn

**Comment by XiaoleiQinn** [comment]
Thank you for your attention! You can download the package from https://github.com/TUM-LMF/MTLCC-pytorch/tree/master/src, then change the code in line 3 sys.path.append('/data/xiaolei.qin/Project/SITSMamba/MTLCC-pytorch-master/src') to your path.

**Comment by clotilda-0** [comment]
code:
   # # ---------------mtlcc dataset-----------------------------
    traindataset = Dataset(datadir, tileids="tileids/eval.tileids")


Error:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/your/data/tileids/eval.tileids'


Requesting Possible solution @XiaoleiQinn 


Requirement for dataset to src/data and model checkpoint to src/checkpoints please

**Comment by clotilda-0** [comment]
In mtlcc dataset -> traindataset = Dataset(datadir,
tileids="tileids/eval.tileids")

FileNotFoundError: [Errno 2] No such file or directory:
'/path/to/your/data/tileids/eval.tileids'
